language: go
sudo: required
go:
  - 1.10.x
  - 1.11.x
  - 1.12beta2
os:
  - linux
  - osx
env:
  matrix:
    - GOARCH=amd64
    - GOARCH=386
  global:
    - DOCKER_HOST=tcp://127.0.0.1:2375
    - DOCKER_PKG_VERSION=18.06.1~ce~3-0~ubuntu
install:
  - make testdeps
  - travis_retry travis-scripts/install-docker.bash
script:
  - travis-scripts/run-tests.bash
services:
  - docker
matrix:
  fast_finish: true
