name: CI

on: [push]
jobs:
  build:
    strategy:
      matrix:
        - macOS-latest
        - ubuntu-latest
        - windows-latest
      go-version:
        - 1.11.12
        - 1.12.7
        - 1.13beta1
    runs-on: ${{matrix.os}}
    env:
      GOPROXY: https://proxy.golang.org
      GO111MODULE: on
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          version: ${{matrix.go-version}}
      - run: go test
